#if __has_include("game_api.h")
#include "game_api.h"
#else
#include "game_api_compat.h"
#endif

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <limits>
#include <type_traits>

namespace {

constexpr int N = 17;
constexpr int NN = N * N;
constexpr int S = 6;
constexpr int API_NPC_SLOTS = static_cast<int>(
    sizeof(((GameInput*)nullptr)->visible_npcs) / sizeof(NpcInfo));
constexpr int MAX_NPCS = 16;
constexpr int MASK_WORDS = 5;
constexpr int MAX_HARVEST = 12;
constexpr int MAX_BEAM_WIDTH = 8;
constexpr int MAX_CANDIDATES = MAX_BEAM_WIDTH * 4;

constexpr float PICK_RATE = 0.65F;
constexpr float BOMB_PCT = 0.10F;
constexpr float TRAMPLE_PCT = 0.05F;
constexpr int TRAMPLE_NPC = 3;
constexpr int FOG = -5;
constexpr int BOMB = -3;
constexpr int OBSTACLE = -1;
constexpr int STAY = 4;
constexpr int CENTER_LO = 4;
constexpr int CENTER_HI = 12;

constexpr int DR[5] = {-1, 1, 0, 0, 0};
constexpr int DC[5] = {0, 0, -1, 1, 0};

constexpr int BEAM_WIDTH = 3;
constexpr float GAMMA = 0.72F;
constexpr float POT_W = 0.35F;
constexpr float DECAY = 0.95F;
constexpr float CENTER_REGEN = 0.1668F;
constexpr float OUTER_REGEN = 0.05F;
constexpr int AGE_CAP = 14;
constexpr float MAX_EST = 60.0F;
constexpr float HOTSPOT_EMA = 0.08F;
constexpr float HOTSPOT_MAX = 2.0F;
constexpr float FOG_STEP = 0.6F;
constexpr int OPENING_SCOUT_ROUNDS = 25;
constexpr int ENDGAME_ROUNDS = 15;

constexpr float INDEX_WEIGHT = 0.75F;
constexpr int INDEX_MAX_STOCK = 60;
constexpr float INDEX_QUANTUM = 0.25F;
constexpr int INDEX_QUARTERS = INDEX_MAX_STOCK * 4 + 1;
constexpr float INDEX_RATES[6] = {0.03F, 0.08F, CENTER_REGEN,
                                  0.40F, 1.0F, 2.0F};
constexpr float INDEX_HAZARDS[3] = {0.0F, 0.12F, 0.30F};
constexpr float BASE_COMP_HAZARD[6] = {0.0F, 0.12F, 0.04F,
                                       0.04F, 0.04F, 0.04F};

constexpr int SCOUT_BOMB_ROUNDS = 5;
constexpr int ROLE_TIE_GAP = 5;
constexpr int ROLE_SWAP_GAP = 20;
constexpr float SCOUT_INFO_BONUS = 0.75F;
constexpr float SCOUT_CLEAR_SHARE = 0.70F;
constexpr float DENIAL_WEIGHT = 0.12F;
constexpr float DENIAL_CAP = 2.0F;

constexpr float BOMB_RATE[6] = {0.0F, 0.0300F, 0.0579F,
                                0.0635F, 0.0535F, 0.0600F};
constexpr float BOMB_PHASE[20] = {
    1.12F, 1.08F, 1.05F, 1.03F, 1.02F,
    1.00F, 0.99F, 0.98F, 0.97F, 0.96F,
    0.95F, 0.93F, 0.92F, 0.90F, 0.88F,
    0.86F, 0.87F, 0.88F, 0.89F, 0.91F,
};

constexpr float VIS_FRAC = 0.15F;
constexpr int VIS_WARMUP = 30;
constexpr float VIS_EMA = 0.05F;
constexpr float BLIND_BONUS = 10.0F;
constexpr float SNAP_LO = 0.15F;
constexpr float SNAP_HI = 10.0F;

// Quarter-unit encoded tables generated by the Bellman subsidy sweep retained
// in strategy.py::_build_index_table.  Loading the .so decodes these once;
// moveDecision performs direct fixed-array lookups only.
constexpr const char* INDEX_HEX[18] = {
    "00060b10151b20252a2f353a3f44494f54595e63696e73787d83888d92979e",
    "00070c11161c21262b30363b40454a50555a5f646a6f74797e84898e93989e",
    "00070c11171c21262b31363b40454b50555a5f656a6f74797f84898e93999e",
    "00050a0f14191e23282d33383d42474d52575c61676c71767b81868b90959e",
    "00060b11161b20252b30353a3f454a4f54595f64696e73797e83888d93989e",
    "00070c11161b21262b30353b40454a4f555a5f64696f74797e83898e93989e",
    "0004080c11161b20252a2f343a3f44494e54595e63686e73787d82888d929e",
    "00060a0f151a1f24292f34393e43494e53585d63686d72777d82878c91979e",
    "00060b11161b20252b30353a3f454a4f54595f64696e73797e83888d93989e",
    "000305090d1115191e23272c31363b40454a50555a5f64696f74797e83889e",
    "0004080d12171c21272c31363b41464b50555b60656a6f757a7f84898f949e",
    "00050a10151a1f24292f34393e43494e53585d63686d72777d82878c91979e",
    "00020305080a0d1114181b1f24282c3035393e42474c51555a5f64696e739e",
    "000305090d11161b20252a2f34393e44494e53585d63686d72777d82878c9e",
    "0004080d12171c21262c31363b40464b50555a60656a6f747a7f84898e949e",
    "000102030507080b0d0f1215181b1f2226292d3134383c4044494d51555a9e",
    "00020406090d1014181c21252a2f34383d42474d52575c61666b70767b809e",
    "0003060a0e13181d22272c31363b41464b50555b60656a6f757a7f84898f9e",
};

inline int cell_of(int row, int col) noexcept { return row * N + col; }
inline int row_of(int cell) noexcept { return cell / N; }
inline int col_of(int cell) noexcept { return cell % N; }
inline bool valid_position(const Position& p) noexcept {
    return p.row >= 0 && p.row < N && p.col >= 0 && p.col < N;
}

inline int region_of(int row, int col) noexcept {
    if (row >= CENTER_LO && row <= CENTER_HI &&
        col >= CENTER_LO && col <= CENTER_HI) return 1;
    if (row <= 3 && col <= 12) return 2;
    if (row >= 4 && col <= 3) return 3;
    if (row >= 13 && col >= 4) return 4;
    return 5;
}

inline bool is_center(int cell) noexcept {
    const int r = row_of(cell), c = col_of(cell);
    return r >= CENTER_LO && r <= CENTER_HI &&
           c >= CENTER_LO && c <= CENTER_HI;
}

inline int rate_class(float rate) noexcept {
    if (rate < 0.055F) return 0;
    if (rate < 0.1234F) return 1;
    if (rate < 0.2834F) return 2;
    if (rate < 0.70F) return 3;
    if (rate < 1.50F) return 4;
    return 5;
}

inline float expected_pickup(float gold) noexcept {
    if (gold <= 0.0F) return 0.0F;
    if (gold < 1.0F) return gold;
    const float value = PICK_RATE * gold + (1.0F - PICK_RATE);
    return std::min(gold, value);
}

inline uint8_t hex_nibble(char c) noexcept {
    return static_cast<uint8_t>(c <= '9' ? c - '0' : c - 'a' + 10);
}

struct Mask289 {
    uint64_t word[MASK_WORDS]{};

    void clear() noexcept { std::memset(word, 0, sizeof(word)); }
    void set(int cell) noexcept { word[cell >> 6] |= uint64_t{1} << (cell & 63); }
    bool test(int cell) const noexcept {
        return (word[cell >> 6] >> (cell & 63)) & uint64_t{1};
    }
    bool intersects(const Mask289& rhs) const noexcept {
        for (int i = 0; i < MASK_WORDS; ++i)
            if (word[i] & rhs.word[i]) return true;
        return false;
    }
    bool operator==(const Mask289& rhs) const noexcept {
        for (int i = 0; i < MASK_WORDS; ++i)
            if (word[i] != rhs.word[i]) return false;
        return true;
    }
};

struct HarvestState {
    Mask289 mask{};
    uint16_t cell[MAX_HARVEST]{};
    float taken[MAX_HARVEST]{};
    uint8_t count = 0;

    float get(int target) const noexcept {
        if (!mask.test(target)) return 0.0F;
        for (int i = 0; i < count; ++i)
            if (cell[i] == target) return taken[i];
        return 0.0F;
    }

    void add(int target, float amount) noexcept {
        for (int i = 0; i < count; ++i) {
            if (cell[i] == target) {
                taken[i] += amount;
                return;
            }
        }
        if (count < MAX_HARVEST) {
            cell[count] = static_cast<uint16_t>(target);
            taken[count] = amount;
            ++count;
            mask.set(target);
        }
    }
};

struct PlanResult {
    float score = -std::numeric_limits<float>::infinity();
    float wealth = 0.0F;
    uint32_t code = 0;
    HarvestState harvest{};
    int final_cell = 0;
    Mask289 cleared{};
};

struct BeamState {
    float score = 0.0F;
    uint32_t uid = 0;
    float utility = 0.0F;
    float wealth = 0.0F;
    int pos = 0;
    HarvestState harvest{};
    Mask289 cleared{};
    uint32_t code = 0;
    bool blind = false;
};

struct JointResult {
    float score = -std::numeric_limits<float>::infinity();
    int position[2]{};
    HarvestState harvest{};
    Mask289 known_bombs{};
    Mask289 cleared{};
};

struct Pending {
    bool valid = false;
    int round = -1;
    int predicted[2]{};
    HarvestState harvest{};
    Mask289 known_bombs{};
    Mask289 traversed{};
};

GameOutput stay_output() noexcept {
    GameOutput out{};
    for (int& action : out.actions) action = STAY;
    out.k = S / 2;
    out.order = 0;
    out.vp = 0;
    return out;
}

class Strategy final {
public:
    Strategy() noexcept { initialize_static_tables(); reset_game(); }

    GameOutput decide(const GameInput& input) noexcept;

private:
    uint8_t dist_[NN][NN]{};
    float gp_[NN][NN]{};
    float decay_pow_[501]{};
    uint8_t index_raw_[18][31]{};
    float priority_lookup_[18][INDEX_QUARTERS]{};
    float priority_ratio_lookup_[18][INDEX_QUARTERS]{};
    float final_priority_[INDEX_QUARTERS]{};
    float final_ratio_[INDEX_QUARTERS]{};
    uint8_t region_[NN]{};
    uint8_t center_[NN]{};

    uint8_t obstacle_[NN]{};
    uint8_t terrain_known_[NN]{};
    uint8_t bomb_[NN]{};
    float gold_known_[NN]{};
    int16_t last_seen_[NN]{};
    int16_t gold_round_[NN]{};
    int16_t bomb_safe_round_[NN]{};
    float outer_rate_[NN]{};
    uint8_t index_rate_class_[NN]{};
    float est_[NN]{};
    float growth_work_[NN]{};
    float priority_[NN]{};
    float priority_ratio_[NN]{};
    float pot_[NN]{};
    int16_t pot_source_[NN]{};

    float region_scale_[6]{};
    float region_remaining_[6]{};
    float region_generated_[6]{};
    float region_collected_[6]{};
    float region_congestion_[6]{};
    float region_competition_[6]{};

    int last_bomb_reset_ = -1;
    int previous_total_ = 0;
    float income_ = 0.0F;
    int vision_spend_ = 0;
    Pending pending_{};
    int role_cycle_ = -1;
    int turn_scout_ = 0;
    int turn_collector_ = 1;
    float scout_bonus_[NN]{};
    float denial_[NN]{};
    float turn_risk_rate_[6]{};
    float turn_fog_penalty_ = 0.0F;
    int round_ = 0;
    int last_round_ = -1;

    void initialize_static_tables() noexcept;
    void reset_game() noexcept;
    void confirm_pending(int round, const int actual[2]) noexcept;
    void observe(const GameInput& input, int round) noexcept;
    void estimate(const GameInput& input, int round) noexcept;
    void index_priority(int round, const int* npcs, int npc_count,
                        const int* enemies, int enemy_count) noexcept;
    void potential() noexcept;
    void classify_roles(int round, const int gold[2], const int position[2],
                        const int* enemies, int enemy_count) noexcept;
    void plan(int start, int unit_gold, int budget, const Mask289& blocked,
              const int npc_count[NN], float pot_weight, int unit_id,
              const HarvestState* pre_harvest, const Mask289& initial_cleared,
              int beam_width, PlanResult result[S + 1]) noexcept;
    JointResult joint_score(const int starts[2], const int gold[2],
                            const int actions[2][S], const int length[2], int order,
                            const Mask289& enemy_mask,
                            const int npc_count[NN], float pot_weight) noexcept;
    int vision(int round, const int gold[2], const int final_cell[2],
               int opponent_gold) noexcept;

    static int next_cell(int cell, int action) noexcept;
    static void decode_actions(uint32_t code, int depth, int* output) noexcept;
    static bool better_beam(const BeamState& a, const BeamState& b) noexcept {
        return a.score > b.score || (a.score == b.score && a.uid > b.uid);
    }
};

static_assert(std::is_standard_layout<GameInput>::value,
              "GameInput must remain a C-compatible standard-layout type");
static_assert(std::is_standard_layout<GameOutput>::value,
              "GameOutput must remain a C-compatible standard-layout type");

void Strategy::initialize_static_tables() noexcept {
    for (int i = 0; i < NN; ++i) {
        const int ir = row_of(i), ic = col_of(i);
        region_[i] = static_cast<uint8_t>(region_of(ir, ic));
        center_[i] = static_cast<uint8_t>(is_center(i));
        for (int j = 0; j < NN; ++j) {
            const int d = std::abs(ir - row_of(j)) + std::abs(ic - col_of(j));
            dist_[i][j] = static_cast<uint8_t>(d);
            gp_[i][j] = std::pow(GAMMA, static_cast<float>(d));
        }
    }
    decay_pow_[0] = 1.0F;
    for (int i = 1; i <= 500; ++i) decay_pow_[i] = decay_pow_[i - 1] * DECAY;

    for (int table = 0; table < 18; ++table) {
        for (int i = 0; i < 31; ++i) {
            const char* text = INDEX_HEX[table] + i * 2;
            index_raw_[table][i] = static_cast<uint8_t>(
                (hex_nibble(text[0]) << 4) | hex_nibble(text[1]));
        }
    }

    const float stock_weight = 1.0F - INDEX_WEIGHT;
    for (int table = 0; table < 18; ++table) {
        for (int quarter = 0; quarter < INDEX_QUARTERS; ++quarter) {
            const float gold = quarter * 0.25F;
            const int lower = quarter / 8;
            const int remainder = quarter % 8;
            float index;
            if (lower >= 30) {
                index = index_raw_[table][30] * INDEX_QUANTUM;
            } else {
                const float fraction = remainder * 0.125F;
                const float encoded = index_raw_[table][lower] + fraction *
                    (index_raw_[table][lower + 1] - index_raw_[table][lower]);
                index = encoded * INDEX_QUANTUM;
            }
            const float value = stock_weight * gold + INDEX_WEIGHT * index;
            priority_lookup_[table][quarter] = value;
            priority_ratio_lookup_[table][quarter] = gold > 0.0F ? value / gold : 0.0F;
        }
    }
    for (int quarter = 0; quarter < INDEX_QUARTERS; ++quarter) {
        const float gold = quarter * 0.25F;
        const float value = stock_weight * gold +
                            INDEX_WEIGHT * expected_pickup(gold);
        final_priority_[quarter] = value;
        final_ratio_[quarter] = gold > 0.0F ? value / gold : 0.0F;
    }
}

void Strategy::reset_game() noexcept {
    std::memset(obstacle_, 0, sizeof(obstacle_));
    std::memset(terrain_known_, 0, sizeof(terrain_known_));
    std::memset(bomb_, 0, sizeof(bomb_));
    std::memset(gold_known_, 0, sizeof(gold_known_));
    std::fill(last_seen_, last_seen_ + NN, int16_t{-1});
    std::fill(gold_round_, gold_round_ + NN, int16_t{-1});
    std::fill(bomb_safe_round_, bomb_safe_round_ + NN, int16_t{-1});
    std::fill(outer_rate_, outer_rate_ + NN, OUTER_REGEN);
    for (int i = 0; i < NN; ++i)
        index_rate_class_[i] = static_cast<uint8_t>(center_[i] ? 2 : rate_class(OUTER_REGEN));
    std::memset(est_, 0, sizeof(est_));
    std::memset(growth_work_, 0, sizeof(growth_work_));
    std::memset(priority_, 0, sizeof(priority_));
    std::memset(priority_ratio_, 0, sizeof(priority_ratio_));
    std::memset(pot_, 0, sizeof(pot_));
    std::fill(pot_source_, pot_source_ + NN, int16_t{-1});
    std::fill(region_scale_, region_scale_ + 6, 1.0F);
    std::memset(region_remaining_, 0, sizeof(region_remaining_));
    std::memset(region_generated_, 0, sizeof(region_generated_));
    std::memset(region_collected_, 0, sizeof(region_collected_));
    std::memset(region_congestion_, 0, sizeof(region_congestion_));
    for (int i = 0; i < 6; ++i) region_competition_[i] = BASE_COMP_HAZARD[i];
    last_bomb_reset_ = -1;
    previous_total_ = 0;
    income_ = 0.0F;
    vision_spend_ = 0;
    pending_ = Pending{};
    role_cycle_ = -1;
    turn_scout_ = 0;
    turn_collector_ = 1;
    std::memset(scout_bonus_, 0, sizeof(scout_bonus_));
    std::memset(denial_, 0, sizeof(denial_));
    std::memset(turn_risk_rate_, 0, sizeof(turn_risk_rate_));
    turn_fog_penalty_ = 0.0F;
    round_ = 0;
}

int Strategy::next_cell(int cell, int action) noexcept {
    if (action < 0 || action > STAY) return -1;
    const int row = row_of(cell) + DR[action];
    const int col = col_of(cell) + DC[action];
    if (row < 0 || row >= N || col < 0 || col >= N) return -1;
    return cell_of(row, col);
}

void Strategy::decode_actions(uint32_t code, int depth, int* output) noexcept {
    for (int i = depth - 1; i >= 0; --i) {
        output[i] = static_cast<int>(code % 5U);
        code /= 5U;
    }
}

void Strategy::confirm_pending(int round, const int actual[2]) noexcept {
    if (!pending_.valid) return;
    const Pending previous = pending_;
    pending_.valid = false;
    if (round != previous.round + 1 ||
        actual[0] != previous.predicted[0] ||
        actual[1] != previous.predicted[1]) return;

    for (int i = 0; i < previous.harvest.count; ++i) {
        const int cell = previous.harvest.cell[i];
        const float left = std::max(0.0F, est_[cell] - previous.harvest.taken[i]);
        gold_known_[cell] = left;
        gold_round_[cell] = static_cast<int16_t>(previous.round);
        const int region = region_[cell];
        region_remaining_[region] =
            std::max(0.0F, region_remaining_[region] - previous.harvest.taken[i]);
    }
    for (int cell = 0; cell < NN; ++cell) {
        if (previous.traversed.test(cell)) {
            terrain_known_[cell] = 1;
            obstacle_[cell] = 0;
            bomb_safe_round_[cell] = static_cast<int16_t>(previous.round);
        }
        if (previous.known_bombs.test(cell)) bomb_[cell] = 0;
    }
}

void Strategy::observe(const GameInput& input, int round) noexcept {
    if (round % 20 == 0 && last_bomb_reset_ != round) {
        std::memset(bomb_, 0, sizeof(bomb_));
        last_bomb_reset_ = round;
    }
    for (int row = 0; row < N; ++row) {
        for (int col = 0; col < N; ++col) {
            const int value = input.grid[row][col];
            if (value == FOG) continue;
            const int cell = cell_of(row, col);
            const float old_gold = gold_known_[cell];
            const int old_round = gold_round_[cell];
            last_seen_[cell] = static_cast<int16_t>(round);
            gold_round_[cell] = static_cast<int16_t>(round);
            terrain_known_[cell] = 1;
            if (value == OBSTACLE) {
                obstacle_[cell] = 1;
                bomb_[cell] = 0;
                gold_known_[cell] = 0.0F;
                bomb_safe_round_[cell] = static_cast<int16_t>(round);
            } else if (value == BOMB) {
                obstacle_[cell] = 0;
                bomb_[cell] = 1;
                gold_known_[cell] = 0.0F;
            } else {
                obstacle_[cell] = 0;
                bomb_[cell] = 0;
                gold_known_[cell] = value > 0 ? static_cast<float>(value) : 0.0F;
                bomb_safe_round_[cell] = static_cast<int16_t>(round);
                if (!center_[cell]) {
                    float sample;
                    if (old_round >= 0) {
                        const int elapsed = std::max(1, round - old_round);
                        sample = std::max(0.0F,
                            (static_cast<float>(value) - old_gold) / elapsed);
                    } else {
                        sample = static_cast<float>(value) / std::max(1, round + 1);
                    }
                    sample = std::min(HOTSPOT_MAX, sample);
                    const float learned = outer_rate_[cell] +
                        HOTSPOT_EMA * (sample - outer_rate_[cell]);
                    outer_rate_[cell] = std::max(0.01F, learned);
                    index_rate_class_[cell] =
                        static_cast<uint8_t>(rate_class(outer_rate_[cell]));
                }
            }
        }
    }
}

void Strategy::estimate(const GameInput& input, int round) noexcept {
    const bool snapshot_valid = input.snapshot_valid != 0;
    float visible_sum[6]{};
    float fixed_sum[6]{};
    float growth_sum[6]{};
    float stock_scale[6] = {1, 1, 1, 1, 1, 1};
    float snapshot_growth_scale[6];
    std::memcpy(snapshot_growth_scale, region_scale_, sizeof(region_scale_));
    const int cycle_start = round - round % 20;

    for (int cell = 0; cell < NN; ++cell) {
        float fixed = 0.0F, growth = 0.0F;
        if (!obstacle_[cell] && !(bomb_[cell] && last_seen_[cell] >= cycle_start)) {
            const int age = round - gold_round_[cell];
            if (age <= 0) {
                fixed = gold_known_[cell];
            } else {
                const int capped_age = std::min(age, AGE_CAP);
                const float regen = center_[cell] ? CENTER_REGEN : outer_rate_[cell];
                fixed = gold_known_[cell] * decay_pow_[std::min(age, 500)];
                growth = regen * capped_age;
            }
        }

        if (snapshot_valid) {
            const int region = region_[cell];
            growth_work_[cell] = growth;
            est_[cell] = fixed;
            if (last_seen_[cell] == round) visible_sum[region] += gold_known_[cell];
            else {
                fixed_sum[region] += fixed;
                growth_sum[region] += growth;
            }
        } else if (last_seen_[cell] == round) {
            est_[cell] = fixed;
        } else {
            est_[cell] = std::min(MAX_EST,
                fixed + growth * region_scale_[region_[cell]]);
        }
    }

    if (!snapshot_valid) return;
    for (int s = 0; s < 5; ++s) {
        const RegionStat& stat = input.snapshot.regions[s];
        const int region = stat.id;
        if (region < 1 || region > 5) continue;
        const float remain = std::max(0, stat.gold_remaining);
        const float generated = std::max(0, stat.gold_generated);
        const float collected = std::max(0, stat.gold_collected);
        const float occupants = std::max(0, stat.occupants);
        const float entered = std::max(0, stat.enter);
        const float left = std::max(0, stat.leave);
        const float congestion = occupants + 0.25F * std::max(0.0F, entered - left);
        region_remaining_[region] = remain;
        region_generated_[region] = generated;
        region_collected_[region] = collected;
        region_congestion_[region] = congestion;

        const float turnover = collected / (collected + remain + 1.0F);
        const float presence = std::min(1.0F, congestion / 7.0F);
        const float target_hazard = std::min(INDEX_HAZARDS[2],
            BASE_COMP_HAZARD[region] + 0.12F * turnover + 0.06F * presence);
        region_competition_[region] = 0.65F * region_competition_[region] +
                                      0.35F * target_hazard;

        const float available = std::max(0.0F, remain - visible_sum[region]);
        if (fixed_sum[region] >= available) {
            stock_scale[region] = fixed_sum[region] > 1e-9F ?
                available / fixed_sum[region] : 0.0F;
            snapshot_growth_scale[region] = 0.0F;
            region_scale_[region] = SNAP_LO;
        } else if (growth_sum[region] > 1e-6F) {
            const float scale = (available - fixed_sum[region]) / growth_sum[region];
            snapshot_growth_scale[region] = std::min(SNAP_HI, std::max(0.0F, scale));
            region_scale_[region] = std::min(SNAP_HI, std::max(SNAP_LO, scale));
        }
    }

    for (int cell = 0; cell < NN; ++cell) {
        if (last_seen_[cell] == round) continue;
        const int region = region_[cell];
        const float value = std::min(MAX_EST,
            est_[cell] * stock_scale[region] +
            growth_work_[cell] * snapshot_growth_scale[region]);
        est_[cell] = value;
        gold_known_[cell] = value;
        gold_round_[cell] = static_cast<int16_t>(round);
    }
}

void Strategy::index_priority(int round, const int* npcs, int npc_count,
                              const int* enemies, int enemy_count) noexcept {
    float local_boost[NN]{};
    for (int n = 0; n < npc_count; ++n) {
        const int rival = npcs[n];
        for (int cell = 0; cell < NN; ++cell) {
            const int distance = dist_[rival][cell];
            if (distance <= 3) local_boost[cell] += 0.04F * (4 - distance);
        }
    }
    for (int n = 0; n < enemy_count; ++n) {
        const int rival = enemies[n];
        for (int cell = 0; cell < NN; ++cell) {
            const int distance = dist_[rival][cell];
            if (distance <= 3) local_boost[cell] += 0.06F * (4 - distance);
        }
    }

    uint8_t region_class[6]{};
    for (int region = 1; region <= 5; ++region) {
        const float hazard = region_competition_[region];
        region_class[region] = static_cast<uint8_t>(
            hazard >= 0.21F ? 2 : hazard >= 0.06F ? 1 : 0);
    }
    const int remaining = 499 - round;
    const float horizon = remaining < ENDGAME_ROUNDS ?
        std::max(0.0F, static_cast<float>(remaining) / ENDGAME_ROUNDS) : 1.0F;

    for (int cell = 0; cell < NN; ++cell) {
        const float gold = est_[cell];
        if (gold <= 0.0F || obstacle_[cell]) {
            priority_[cell] = priority_ratio_[cell] = 0.0F;
            continue;
        }
        const int region = region_[cell];
        int hazard_class = region_class[region];
        if (local_boost[cell] > 0.0F) {
            const float hazard = region_competition_[region] + local_boost[cell];
            hazard_class = hazard >= 0.21F ? 2 : hazard >= 0.06F ? 1 : 0;
        }
        const int table = index_rate_class_[cell] * 3 + hazard_class;
        const int quarter = std::min(INDEX_QUARTERS - 1,
            std::max(0, static_cast<int>(gold * 4.0F + 0.5F)));
        float value = priority_lookup_[table][quarter];
        float ratio = priority_ratio_lookup_[table][quarter];
        if (horizon < 1.0F) {
            value = final_priority_[quarter] +
                    horizon * (value - final_priority_[quarter]);
            ratio = final_ratio_[quarter] +
                    horizon * (ratio - final_ratio_[quarter]);
        }
        value = std::min(64.0F, std::max(0.0F, value));
        priority_[cell] = value;
        priority_ratio_[cell] = gold > INDEX_MAX_STOCK ? value / gold : ratio;
    }
}

void Strategy::potential() noexcept {
    for (int cell = 0; cell < NN; ++cell) {
        pot_[cell] = priority_[cell];
        pot_source_[cell] = priority_[cell] > 0.0F ?
            static_cast<int16_t>(cell) : int16_t{-1};
    }
    for (int row = 0; row < N; ++row) {
        for (int col = 1; col < N; ++col) {
            const int cell = cell_of(row, col);
            const float value = pot_[cell - 1] * GAMMA;
            if (value > pot_[cell]) {
                pot_[cell] = value;
                pot_source_[cell] = pot_source_[cell - 1];
            }
        }
        for (int col = N - 2; col >= 0; --col) {
            const int cell = cell_of(row, col);
            const float value = pot_[cell + 1] * GAMMA;
            if (value > pot_[cell]) {
                pot_[cell] = value;
                pot_source_[cell] = pot_source_[cell + 1];
            }
        }
    }
    for (int row = 1; row < N; ++row) {
        for (int col = 0; col < N; ++col) {
            const int cell = cell_of(row, col);
            const float value = pot_[cell - N] * GAMMA;
            if (value > pot_[cell]) {
                pot_[cell] = value;
                pot_source_[cell] = pot_source_[cell - N];
            }
        }
    }
    for (int row = N - 2; row >= 0; --row) {
        for (int col = 0; col < N; ++col) {
            const int cell = cell_of(row, col);
            const float value = pot_[cell + N] * GAMMA;
            if (value > pot_[cell]) {
                pot_[cell] = value;
                pot_source_[cell] = pot_source_[cell + N];
            }
        }
    }
    for (int cell = 0; cell < NN; ++cell) {
        if (obstacle_[cell]) {
            pot_[cell] = 0.0F;
            pot_source_[cell] = -1;
        }
    }
}

void Strategy::classify_roles(int round, const int gold[2], const int position[2],
                              const int* enemies, int enemy_count) noexcept {
    const int cycle = round / 20;
    int scout = turn_scout_;
    if (cycle != role_cycle_) {
        if (gold[0] + ROLE_TIE_GAP < gold[1]) scout = 0;
        else if (gold[1] + ROLE_TIE_GAP < gold[0]) scout = 1;
        else if (enemy_count > 0) {
            int d0 = 255, d1 = 255;
            for (int i = 0; i < enemy_count; ++i) {
                d0 = std::min(d0, static_cast<int>(dist_[position[0]][enemies[i]]));
                d1 = std::min(d1, static_cast<int>(dist_[position[1]][enemies[i]]));
            }
            scout = d0 <= d1 ? 0 : 1;
        } else {
            int fog[2]{};
            for (int unit = 0; unit < 2; ++unit)
                for (int cell = 0; cell < NN; ++cell)
                    if (dist_[position[unit]][cell] <= S && !terrain_known_[cell])
                        ++fog[unit];
            scout = fog[0] >= fog[1] ? 0 : 1;
        }
        role_cycle_ = cycle;
    } else {
        const int other = 1 - scout;
        if (gold[scout] > gold[other] + ROLE_SWAP_GAP) scout = other;
    }
    const int collector = 1 - scout;
    turn_scout_ = scout;
    turn_collector_ = collector;

    const int phase = round % 20;
    const int future = 499 - round;
    float info_strength = round < OPENING_SCOUT_ROUNDS ? 1.0F :
                          phase < SCOUT_BOMB_ROUNDS ? 0.60F : 0.0F;
    if (future < ENDGAME_ROUNDS)
        info_strength *= std::max(0.0F, static_cast<float>(future) / ENDGAME_ROUNDS);
    const float clear_strength = phase < SCOUT_BOMB_ROUNDS ? 1.0F : 0.0F;
    std::memset(scout_bonus_, 0, sizeof(scout_bonus_));

    const int cycle_start = round - phase;
    const int scout_loss = gold[scout] > 0 ?
        static_cast<int>(std::ceil(BOMB_PCT * gold[scout])) : 0;
    const int collector_loss = gold[collector] > 0 ?
        static_cast<int>(std::ceil(BOMB_PCT * gold[collector])) : 0;
    const int loss_gap = collector_loss - scout_loss;
    if (info_strength > 0.0F || (loss_gap > 0 && clear_strength > 0.0F)) {
        for (int cell = 0; cell < NN; ++cell) {
            if (dist_[position[scout]][cell] > S || obstacle_[cell]) continue;
            float bonus = !terrain_known_[cell] ?
                SCOUT_INFO_BONUS * info_strength : 0.0F;
            if (loss_gap > 0 && bomb_safe_round_[cell] < cycle_start) {
                const float probability = bomb_[cell] ? 1.0F :
                    turn_risk_rate_[region_[cell]];
                if (probability > 0.0F) {
                    const float relevance = dist_[position[collector]][cell] <= S ?
                        1.0F : 0.25F;
                    const float target_weight = std::min(1.0F, 0.25F + pot_[cell] / 6.0F);
                    bonus += SCOUT_CLEAR_SHARE * clear_strength * loss_gap *
                             probability * relevance * target_weight;
                }
            }
            scout_bonus_[cell] = bonus;
        }
    }

    std::memset(denial_, 0, sizeof(denial_));
    for (int e = 0; e < enemy_count; ++e) {
        struct Target { float value; int cell; } target[4];
        int count = 0;
        const int enemy = enemies[e];
        for (int action = 0; action < 4; ++action) {
            const int cell = next_cell(enemy, action);
            if (cell < 0 || obstacle_[cell] || dist_[position[scout]][cell] > S) continue;
            target[count++] = Target{pot_[cell] + est_[cell], cell};
        }
        std::sort(target, target + count,
                  [](const Target& a, const Target& b) { return a.value > b.value; });
        for (int rank = 0; rank < std::min(2, count); ++rank) {
            if (target[rank].value <= 0.0F) continue;
            float bonus = std::min(DENIAL_CAP, DENIAL_WEIGHT * target[rank].value);
            if (rank) bonus *= 0.55F;
            denial_[target[rank].cell] = std::max(denial_[target[rank].cell], bonus);
        }
    }
}

void Strategy::plan(int start, int unit_gold, int budget, const Mask289& blocked,
                    const int npc_count[NN], float pot_weight, int unit_id,
                    const HarvestState* pre_harvest,
                    const Mask289& initial_cleared, int beam_width,
                    PlanResult result[S + 1]) noexcept {
    const bool is_scout = unit_id == turn_scout_;
    HarvestState initial_harvest{};
    if (pre_harvest) initial_harvest = *pre_harvest;
    float initial_potential = pot_[start];
    const int source = pot_source_[start];
    if (source >= 0) {
        const float taken = initial_harvest.get(source);
        if (taken > 0.0F) {
            const float left = std::max(0.0F, est_[source] - taken);
            initial_potential = left * priority_ratio_[source] * gp_[start][source];
        }
    }
    float base = pot_weight * initial_potential;
    if (is_scout) base += denial_[start];
    for (int depth = 0; depth <= budget; ++depth) {
        result[depth] = PlanResult{};
        result[depth].score = base;
        result[depth].harvest = initial_harvest;
        result[depth].final_cell = start;
        result[depth].cleared = initial_cleared;
    }

    BeamState beam[MAX_BEAM_WIDTH]{};
    int beam_count = 1;
    beam[0].score = base;
    beam[0].uid = 0;
    beam[0].pos = start;
    beam[0].harvest = initial_harvest;
    beam[0].cleared = initial_cleared;
    uint32_t next_uid = 1;
    const int cycle_start = round_ - round_ % 20;

    for (int depth = 1; depth <= budget; ++depth) {
        BeamState candidate[MAX_CANDIDATES]{};
        int candidate_count = 0;
        for (int b = 0; b < beam_count; ++b) {
            const BeamState& state = beam[b];
            if (state.blind) continue;
            const float held = unit_gold + state.wealth;
            const float bomb_penalty = held > 0.0F ? std::ceil(BOMB_PCT * held) : 0.0F;
            for (int action = 0; action < 4; ++action) {
                const int next = next_cell(state.pos, action);
                if (next < 0 || obstacle_[next] || blocked.test(next)) continue;

                BeamState updated = state;
                updated.pos = next;
                updated.uid = next_uid;
                updated.code = state.code * 5U + static_cast<uint32_t>(action);
                const float taken = state.harvest.get(next);
                const float available = est_[next] - taken;
                float pickup = 0.0F;
                if (available > 1e-9F) {
                    if (last_seen_[next] == round_) pickup = std::ceil(PICK_RATE * available);
                    else if (available < 1.0F) pickup = available;
                    else pickup = std::min(available, PICK_RATE * available + 0.35F);
                    updated.harvest.add(next, pickup);
                }
                updated.utility += pickup;
                updated.wealth += pickup;

                const bool first_visit = !state.cleared.test(next);
                updated.cleared.set(next);
                if (first_visit) {
                    float loss = 0.0F;
                    if (bomb_[next]) loss = bomb_penalty;
                    else if (bomb_safe_round_[next] < cycle_start && bomb_penalty > 0.0F)
                        loss = turn_risk_rate_[region_[next]] * bomb_penalty;
                    updated.utility -= loss;
                    updated.wealth -= loss;
                    if (is_scout) updated.utility += scout_bonus_[next];
                }
                if (npc_count[next] >= TRAMPLE_NPC) {
                    const float after = unit_gold + updated.wealth;
                    const float loss = after > 0.0F ? std::ceil(TRAMPLE_PCT * after) : 0.0F;
                    updated.utility -= loss;
                    updated.wealth -= loss;
                }
                updated.blind = !terrain_known_[next];
                if (updated.blind) updated.utility -= turn_fog_penalty_;

                float terminal = pot_[next];
                const int terminal_source = pot_source_[next];
                if (terminal_source >= 0) {
                    const float source_taken = updated.harvest.get(terminal_source);
                    if (source_taken > 0.0F) {
                        const float left = std::max(0.0F,
                            est_[terminal_source] - source_taken);
                        terminal = left * priority_ratio_[terminal_source] *
                                   gp_[next][terminal_source];
                    }
                }
                updated.score = updated.utility + pot_weight * terminal;
                if (is_scout) updated.score += denial_[next];

                int duplicate = -1;
                for (int i = 0; i < candidate_count; ++i) {
                    if (candidate[i].pos == updated.pos &&
                        candidate[i].harvest.mask == updated.harvest.mask &&
                        candidate[i].cleared == updated.cleared) {
                        duplicate = i;
                        break;
                    }
                }
                if (duplicate < 0) {
                    if (candidate_count < MAX_CANDIDATES)
                        candidate[candidate_count++] = updated;
                    ++next_uid;
                } else if (updated.score > candidate[duplicate].score) {
                    candidate[duplicate] = updated;
                    ++next_uid;
                }
            }
        }

        if (candidate_count == 0) {
            for (int rest = depth; rest <= budget; ++rest) {
                result[rest] = result[rest - 1];
                result[rest].code = result[rest - 1].code * 5U + STAY;
            }
            break;
        }

        std::sort(candidate, candidate + candidate_count, better_beam);
        beam_count = 0;
        if (beam_width <= 4 && candidate_count > beam_width) {
            bool endpoint_used[NN]{};
            for (int i = 0; i < candidate_count && beam_count < beam_width; ++i) {
                if (!endpoint_used[candidate[i].pos]) {
                    beam[beam_count++] = candidate[i];
                    endpoint_used[candidate[i].pos] = true;
                }
            }
            if (beam_count < beam_width) {
                for (int i = 0; i < candidate_count && beam_count < beam_width; ++i) {
                    bool selected = false;
                    for (int j = 0; j < beam_count; ++j)
                        if (beam[j].uid == candidate[i].uid) selected = true;
                    if (!selected) beam[beam_count++] = candidate[i];
                }
            }
        } else {
            beam_count = std::min({beam_width, candidate_count, MAX_BEAM_WIDTH});
            for (int i = 0; i < beam_count; ++i) beam[i] = candidate[i];
        }

        const BeamState& best = beam[0];
        result[depth].score = best.score;
        result[depth].wealth = best.wealth;
        result[depth].code = best.code;
        result[depth].harvest = best.harvest;
        result[depth].final_cell = best.pos;
        result[depth].cleared = best.cleared;
        if (result[depth - 1].score > result[depth].score) {
            result[depth] = result[depth - 1];
            result[depth].code = result[depth - 1].code * 5U + STAY;
        }
    }
}

JointResult Strategy::joint_score(const int starts[2], const int gold[2],
                                  const int actions[2][S], const int length[2],
                                  int order, const Mask289& enemy_mask,
                                  const int npc_count[NN],
                                  float pot_weight) noexcept {
    JointResult result{};
    result.position[0] = starts[0];
    result.position[1] = starts[1];
    float wallet[2] = {static_cast<float>(gold[0]), static_cast<float>(gold[1])};
    float utility = 0.0F;
    const int cycle_start = round_ - round_ % 20;

    for (int pass = 0; pass < 2; ++pass) {
        const int unit = pass == 0 ? order : 1 - order;
        const int other = 1 - unit;
        for (int step = 0; step < length[unit]; ++step) {
            const int action = actions[unit][step];
            if (action == STAY) continue;
            const int next = next_cell(result.position[unit], action);
            if (next < 0 || obstacle_[next] || enemy_mask.test(next) ||
                next == result.position[other]) continue;
            result.position[unit] = next;
            const float wallet_before = wallet[unit];

            const float taken = result.harvest.get(next);
            const float available = est_[next] - taken;
            if (available > 1e-9F) {
                float pickup;
                if (last_seen_[next] == round_) pickup = std::ceil(PICK_RATE * available);
                else if (available < 1.0F) pickup = available;
                else pickup = std::min(available, PICK_RATE * available + 0.35F);
                result.harvest.add(next, pickup);
                utility += pickup;
                wallet[unit] += pickup;
            }

            const bool first_visit = !result.cleared.test(next);
            if (first_visit) {
                const float bomb_penalty = wallet_before > 0.0F ?
                    std::ceil(BOMB_PCT * wallet_before) : 0.0F;
                float loss = 0.0F;
                if (bomb_[next]) {
                    loss = bomb_penalty;
                    result.known_bombs.set(next);
                } else if (bomb_safe_round_[next] < cycle_start && bomb_penalty > 0.0F) {
                    loss = turn_risk_rate_[region_[next]] * bomb_penalty;
                }
                utility -= loss;
                wallet[unit] -= loss;
                if (unit == turn_scout_) utility += scout_bonus_[next];
            }
            result.cleared.set(next);

            if (npc_count[next] >= TRAMPLE_NPC) {
                const float loss = wallet[unit] > 0.0F ?
                    std::ceil(TRAMPLE_PCT * wallet[unit]) : 0.0F;
                utility -= loss;
                wallet[unit] -= loss;
            }
            if (!terrain_known_[next]) utility -= turn_fog_penalty_;
        }
    }

    float future[2]{};
    int source[2] = {-1, -1};
    for (int unit = 0; unit < 2; ++unit) {
        const int cell = result.position[unit];
        future[unit] = pot_[cell];
        source[unit] = pot_source_[cell];
        if (source[unit] >= 0) {
            const float taken = result.harvest.get(source[unit]);
            if (taken > 0.0F) {
                const float left = std::max(0.0F, est_[source[unit]] - taken);
                future[unit] = left * priority_ratio_[source[unit]] *
                               gp_[cell][source[unit]];
            }
        }
    }
    float future_value;
    if (source[0] >= 0 && source[0] == source[1]) {
        const float high = std::max(future[0], future[1]);
        const float low = std::min(future[0], future[1]);
        future_value = high + 0.35F * low;
    } else {
        future_value = future[0] + future[1];
    }
    utility += denial_[result.position[turn_scout_]];
    result.score = utility + pot_weight * future_value;
    return result;
}

int Strategy::vision(int round, const int gold[2], const int final_cell[2],
                     int opponent_gold) noexcept {
    const int total = gold[0] + gold[1];
    int delta = total - previous_total_;
    previous_total_ = total;
    if (round > 0) {
        if (delta < 0) delta = 0;
        income_ += VIS_EMA * (delta - income_);
    }
    if (round < VIS_WARMUP || round >= 499) return 0;
    const int lead = total - vision_spend_ - opponent_gold;
    const float posture = lead < 0 ? 1.20F : lead > 50 ? 0.75F : 1.0F;
    const float budget = posture * VIS_FRAC * income_;
    if (budget >= 3.0F) {
        vision_spend_ += 3;
        return 2;
    }
    if (budget >= 2.0F) {
        vision_spend_ += 2;
        return 1;
    }
    if (income_ >= BLIND_BONUS) {
        for (int unit = 0; unit < 2; ++unit) {
            const int row0 = row_of(final_cell[unit]);
            const int col0 = col_of(final_cell[unit]);
            for (int dr = -3; dr <= 3; ++dr) {
                const int row = row0 + dr;
                if (row < 0 || row >= N) continue;
                for (int dc = -3; dc <= 3; ++dc) {
                    const int col = col0 + dc;
                    if (col >= 0 && col < N && est_[cell_of(row, col)] >= 2.0F)
                        return 0;
                }
            }
        }
        vision_spend_ += 2;
        return 1;
    }
    return 0;
}

GameOutput Strategy::decide(const GameInput& input) noexcept {
    GameOutput output = stay_output();
    const int round = input.round;
    if (round < 0 || round > 499) return output;
    if (round == 0 && last_round_ >= 0) reset_game();
    round_ = round;
    last_round_ = round;

    if (!valid_position(input.my_units[0]) ||
        !valid_position(input.my_units[1])) return output;
    const int position[2] = {
        cell_of(input.my_units[0].row, input.my_units[0].col),
        cell_of(input.my_units[1].row, input.my_units[1].col),
    };
    const int gold[2] = {
        std::max(0, input.my_units_gold[0]),
        std::max(0, input.my_units_gold[1]),
    };
    confirm_pending(round, position);

    int npcs[MAX_NPCS]{};
    int npc_total = 0;
    const int reported_npcs = std::min({MAX_NPCS, API_NPC_SLOTS,
                                        std::max(0, input.num_visible_npcs)});
    for (int i = 0; i < reported_npcs; ++i) {
        if (input.visible_npcs[i].id != 0 && valid_position(input.visible_npcs[i].pos))
            npcs[npc_total++] = cell_of(input.visible_npcs[i].pos.row,
                                        input.visible_npcs[i].pos.col);
    }
    int enemies[2]{};
    int enemy_total = 0;
    for (const Position& enemy : input.visible_enemies)
        if (valid_position(enemy)) enemies[enemy_total++] = cell_of(enemy.row, enemy.col);

    observe(input, round);
    estimate(input, round);
    index_priority(round, npcs, npc_total, enemies, enemy_total);
    potential();

    Mask289 enemy_mask{};
    for (int i = 0; i < enemy_total; ++i) enemy_mask.set(enemies[i]);
    int npc_count[NN]{};
    for (int i = 0; i < npc_total; ++i) ++npc_count[npcs[i]];

    const int future = 499 - round;
    float pot_weight = POT_W;
    if (future < ENDGAME_ROUNDS)
        pot_weight *= std::max(0.0F, static_cast<float>(future) / ENDGAME_ROUNDS);
    float risk_multiplier = round < OPENING_SCOUT_ROUNDS ? 0.0F : 1.0F;
    if (future < ENDGAME_ROUNDS)
        risk_multiplier *= 1.0F +
            static_cast<float>(ENDGAME_ROUNDS - future) / ENDGAME_ROUNDS;
    const float phase = BOMB_PHASE[round % 20] * risk_multiplier;
    for (int region = 0; region < 6; ++region)
        turn_risk_rate_[region] = BOMB_RATE[region] * phase;
    turn_fog_penalty_ = round < OPENING_SCOUT_ROUNDS ? 0.0F : FOG_STEP;
    classify_roles(round, gold, position, enemies, enemy_total);

    const Mask289 empty_mask{};
    PlanResult curve[2][S + 1];
    plan(position[0], gold[0], S, enemy_mask, npc_count, pot_weight, 0,
         nullptr, empty_mask, BEAM_WIDTH, curve[0]);
    plan(position[1], gold[1], S, enemy_mask, npc_count, pot_weight, 1,
         nullptr, empty_mask, BEAM_WIDTH, curve[1]);

    int path[2][S + 1][S]{};
    for (int depth = 0; depth <= S; ++depth) {
        for (int unit = 0; unit < 2; ++unit) {
            for (int step = 0; step < S; ++step) path[unit][depth][step] = STAY;
            decode_actions(curve[unit][depth].code, depth, path[unit][depth]);
        }
    }

    float best_score = -std::numeric_limits<float>::infinity();
    int best_k = S / 2;
    int best_order = 0;
    int best_actions[2][S]{};
    int best_length[2]{};
    JointResult best_result{};

    for (int k = 0; k <= S; ++k) {
        int actions[2][S]{};
        int length[2] = {k, S - k};
        for (int step = 0; step < k; ++step) actions[0][step] = path[0][k][step];
        for (int step = 0; step < S - k; ++step)
            actions[1][step] = path[1][S - k][step];
        const bool order_matters = curve[0][k].cleared.intersects(curve[1][S - k].cleared) ||
            curve[0][k].cleared.test(position[1]) ||
            curve[1][S - k].cleared.test(position[0]);
        const int order_count = order_matters ? 2 : 1;
        for (int order = 0; order < order_count; ++order) {
            const JointResult result = joint_score(position, gold, actions, length,
                                                   order, enemy_mask, npc_count,
                                                   pot_weight);
            if (result.score > best_score) {
                best_score = result.score;
                best_k = k;
                best_order = order;
                best_result = result;
                best_length[0] = length[0];
                best_length[1] = length[1];
                std::memcpy(best_actions, actions, sizeof(best_actions));
            }
        }
    }

    bool interaction = curve[0][best_k].harvest.mask.intersects(
                           curve[1][S - best_k].harvest.mask) ||
                       best_result.position[0] != curve[0][best_k].final_cell ||
                       best_result.position[1] != curve[1][S - best_k].final_cell;
    if (interaction) {
        const int first = best_order;
        const int second = 1 - best_order;
        int candidate_k[2] = {best_k,
            best_k + (second == 0 ? 1 : -1)};
        const int candidate_count = candidate_k[1] >= 0 && candidate_k[1] <= S ? 2 : 1;
        for (int candidate = 0; candidate < candidate_count; ++candidate) {
            const int coordinated_k = candidate_k[candidate];
            int budget[2] = {coordinated_k, S - coordinated_k};
            if (budget[second] <= 0) continue;
            int coordinated[2][S]{};
            for (int step = 0; step < budget[0]; ++step)
                coordinated[0][step] = path[0][budget[0]][step];
            for (int step = 0; step < budget[1]; ++step)
                coordinated[1][step] = path[1][budget[1]][step];

            int lead_actions[2][S]{};
            int lead_length[2]{};
            lead_length[first] = budget[first];
            for (int step = 0; step < budget[first]; ++step)
                lead_actions[first][step] = coordinated[first][step];
            const JointResult lead = joint_score(position, gold, lead_actions,
                                                  lead_length, best_order,
                                                  enemy_mask, npc_count,
                                                  pot_weight);
            Mask289 blocked = enemy_mask;
            blocked.set(lead.position[first]);
            PlanResult tail[S + 1];
            plan(position[second], gold[second], budget[second], blocked,
                 npc_count, pot_weight, second, &lead.harvest, lead.cleared,
                 std::max(6, BEAM_WIDTH), tail);
            decode_actions(tail[budget[second]].code, budget[second],
                           coordinated[second]);
            const JointResult result = joint_score(position, gold, coordinated,
                                                    budget, best_order,
                                                    enemy_mask, npc_count,
                                                    pot_weight);
            if (result.score > best_result.score) {
                best_score = result.score;
                best_k = coordinated_k;
                best_result = result;
                best_length[0] = budget[0];
                best_length[1] = budget[1];
                std::memcpy(best_actions, coordinated, sizeof(best_actions));
            }
        }
    }

    pending_ = Pending{};
    pending_.valid = true;
    pending_.round = round;
    pending_.predicted[0] = best_result.position[0];
    pending_.predicted[1] = best_result.position[1];
    pending_.harvest = best_result.harvest;
    pending_.known_bombs = best_result.known_bombs;
    pending_.traversed = best_result.cleared;

    int cursor = 0;
    for (int step = 0; step < best_length[0]; ++step)
        output.actions[cursor++] = best_actions[0][step];
    for (int step = 0; step < best_length[1]; ++step)
        output.actions[cursor++] = best_actions[1][step];
    while (cursor < S) output.actions[cursor++] = STAY;
    output.k = best_k;
    output.order = best_order;
    output.vp = vision(round, gold, best_result.position, std::max(0, input.gold_opp));
    return output;
}

Strategy strategy_instance;

}  // namespace

#if defined(__GNUC__)
#define GOLD_RUSH_EXPORT __attribute__((visibility("default")))
#else
#define GOLD_RUSH_EXPORT
#endif

extern "C" GOLD_RUSH_EXPORT GameOutput moveDecision(const GameInput* input) noexcept {
    const GameOutput fallback = stay_output();
    if (input == nullptr) return fallback;
    try {
        const GameOutput result = strategy_instance.decide(*input);
        for (const int action : result.actions)
            if (action < 0 || action > STAY) return fallback;
        if (result.k < 0 || result.k > S ||
            (result.order != 0 && result.order != 1) ||
            result.vp < 0 || result.vp > 2) return fallback;
        return result;
    } catch (...) {
        return fallback;
    }
}
